version: '3.8'

services:
  db:
    image: mariadb:latest
    platform: linux/arm/v7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 11111111
      MYSQL_DATABASE: logger
      MYSQL_USER: user
      MYSQL_PASSWORD: 11111111
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: 11111111
      DB_NAME: logger
    volumes:
      - ./:/var/www/app

volumes:
  db_data:
